# Generated by Django 5.2.3 on 2025-06-27 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_category_options_alter_subcategory_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subcategory",
            options={
                "ordering": ["category__name", "name"],
                "verbose_name": "Подкатегория",
                "verbose_name_plural": "Подкатегории",
            },
        ),
    ]
